### ISSUE TITLE
Client side Whitelisting is to restrictive.

### ISSUE THREAD

**Issue by KebHelion** [kasenvr/project-athena#102]
Client side Whitelisting is to restrictive. It kills literally the experience put in place on a domain by its creator. Users come to a domain without the scripts access in it's the whitelist so nothing works. A notification would be another level of pain. 
_(Imagine have to accept all the javascript running on every single page on the web. Doesn't make too much sense, right? Why we would have the same here? )_

Instead I would suggest this:

Have a "**Domain Side Whitelist**", where the domain owner define the whithelist for what is expected to run on his domain.

The "**Client Side Whitelist**" still exist.

But, instead of only the Client side list, the Whitelist to be applied would be: 

   **{Domain Side Whitelist} + {Client Side Whitelist}** 

This way, we would be protected from Troll's script that harm our preferred place in the metaverse.
We won't be from Troll's Domain. But well... Just don't go there.

All other possible breach should be addressed outside of this issue. "Settings" for example, should not be modifiable by scripting.

**Comment by kasenvr** [comment]
This is a really good thought and has been brought up before. 

I suppose the question is... How should we approach this at current? One such idea was to place an entity close to wherever a user enters the domain at that has a list of the script URLs to whitelist in it, then it is the domain owner's responsibility to lock it and make sure no one with lock/unlock rights changes that for malicious purposes.

Then basically the client will auto pass those scripts for that domain.

It would also be necessary to make sure no one spoofs that secured object on a public building domain.

**Comment by KebHelion** [comment]
Not extremely intuitive to figure, but I see where you go.

So why not an "Entity Script White List" group of attributes on the zone Entity (Like we have for Keylight, Haze, etc.) 
It could be easier to manage.

**Comment by MarcusLlewellyn** [comment]
Eventually, and hopefully sooner rather than later, I'd like to see the interface behave more like a web browser when it comes to script security. The hurdle there is that we need to replace the Qt script engine with something that has support for security contexts like V8. This way we can run scripts hosted by a domain in a trusted manner in one context, and foreign scripts in a less trusted context.

**Comment by kasenvr** [comment]
Keb, that does seem like a good idea to go with. Being spatially aware instead of domain-aware to determine what scripts run in what context (pass or fail.)

@MarcusLlewellyn that would for sure be a nice way to go once we get that going WRT V8. However, is it not trivially possible for the client to receive that list of trusted domains from the host domain and run them by default? I suppose that's what we're doing by this zone method, and ideally I think using the zone method + a whole domain list would be good because then it allows for better subleasing later since others can elevate their own domains in their own sub-spaces.

**Comment by KebHelion** [comment]
I wonder how it would works...
When we enter in a zone, the entities might be already loaded (currently I think they are), but their script get initially refused to run. Are we going to re-check if some of them need to be started? (Doing this may be not very performant.)

I think we better get this white list at the second we enter on a domain, (from the server), before it starts to deal with scripts. So have this configured on the server.
Can't we call the server to get that list?

**Comment by kasenvr** [comment]
https://github.com/kasenvr/project-athena/pull/112

Whitelist is now disabled by default, it has a toggle to enable or disable. Though ways to have the server send a list of trusted domains to the client will still need to be implemented. Probably would not be the hardest thing in the world to do, but that transfer of information needs to be had and registered before the domain's entities load.

**Comment by kasenvr** [comment]
Closing this issue for now because PR 112 takes care of this, if still desired, it would be best to open a PR about expanding the whitelist security capabilities by having security contexts and communication passed from the server, or other ideas like that. :)
