### ISSUE TITLE
We need shader documentation!

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#136]
In the main log, when there's a bug you get a dump of 1000 lines, on the 1000th line or so that's when your actual shader code can be found to start.

That's not the worst, but we need shader docs. Odysseus (thank you for the tip!) has had to reverse engineer a lot of info about what High Fidelity gives us to work with on the shaders from that, Marcus does have about 1/3 of this listed but not fully documented what they do.

We need to start with at least that and make a documentation piece for shaders on this, even if it's minimal and not fully complete to start. We need to lay the groundwork and get that going at docs.projectathena.dev

**Comment by kasenvr** [comment]
I am willing to setup the initial documentation if I can be given the information to put in it or am pointed in the right direction. :)

**Comment by HifiExperiments** [comment]
I can provide a bunch of details for this

**Comment by MarcusLlewellyn** [comment]
I did start some basic documentation in a Google doc. I mined as much as I could from Hifi forums posts, examples on Gist, and from the source code.

I am far from an experienced shader coder, though. If someone want to take what I have now and spruce it up (and no doubt correct it) please do! The link to the document is below.

[Project Athena Shader Documentation (DRAFT)](https://docs.google.com/document/d/1REJjSydPDK3IArYDKpNjkwyJPhM_UEUCA53soVAvr9Y/edit?usp=sharing)

**Comment by odysseus654** [comment]
It's at least partially helpful (until we get tired of the spam) that all the GLSL include files are dumped every time there's a bug in shader code.  The problem is figuring out what's important/relevant, and what the actual meaning of each of the functions are (outside of variable names)

I did try to start building a list of potentially-useful things to know (trying to filter out stuff that appears visible through more obvious means) but it's by no means complete: https://docs.google.com/document/d/1NwGUt7hyP-vyDaDgpE5f6RgJiw4R1z_6fB_qerrtX1o/edit

**Comment by HifiExperiments** [comment]
This overlaps a lot with the above, but here's my overview of the (current) state of things:
# Procedural Shaders

Athena allows you to apply custom fragment and vertex shaders to objects via material entities.  Currently, procedural shaders only work on models (entities and avatars), shape entities, and zone entities.

Shaders are written in GLSL.  To enable shaders on meshes, you must enable Developer -> Render -> Enable Procedural Materials.

To create a Procedural Material Entity, you can create a material entity like this (you can also provide a real material URL):

```
Entities.addEntity({
	type: "Material",
	materialURL: "materialData",
	priority: 1,
	materialData: JSON.stringify({
		materials: {
			"model": "hifi_shader_simple"
			"procedural": {
			  	"version": 2,
			  	"shaderUrl": "https://gist.githubusercontent.com/SamGondelman/1698eaf73d86d6a0c9238abff0116e8d/raw/1aa938de50c1b6f31af8a122f40a7ce331eeb533/Proceduralv2.fs"
			}
		}
	})
});
```

You must specify the material "model" as "hifi_shader_simple" and provide a shader link.  To provide a fragment shader, set "fragmentShaderURL" (or "shaderUrl").  To provide a vertex shader, set "vertexShaderURL".

## Fragment Shaders

Athena supports multiple versions of fragment shaders.  The version is specified in the material data, otherwise it defaults to version 1.  Each shader version supports the same global variables but must implement a slightly different method.

### Provided variables

The following global variables are provided:

- vec4 iDate;					// year, month (0 based to match shadertoy), day, seconds
- vec3 iWorldPosition; 	 		// entity position
- mat3 iWorldOrientation;		// entity orientation
- vec3 iWorldScale;     		// entity scale
- float iGlobalTime;			// time since last shader recompilation
- float iLocalCreatedTime;		// time since first shader compilation
- float iEntityTime;			// time since entity creation
- int iFrameCount;				// frames since last shader recompilation
- sampler2D iChannel0, iChannel1, iChannel2, iChannel3; // custom textures, if provided
- vec3 iChannelResolution[4];	// resolution of each custom texture, if provided

The following variables are defined but currently not implemented:
- vec3 iResolution;
- vec4 iMouse;
- float iSampleRate;
- vec4 iChannelTime;

The following per-fragment uniforms are also provided:

- vec4 _positionMS; (equal to _position)
- vec4 _positionES; (equal to _eyePosition)
- vec3 _normalMS; (equal to _modelNormal)
- vec3 _normalWS; (equal to _normal)
- vec4 _color;
- vec4 _texCoord01 (also split into vec2_texCoord0 and vec2 _texCoord1)

### Provided methods, constants, and structs

- float mod289(float x);
- vec2 mod289(vec2 x);
- vec3 mod289(vec3 x);
- vec4 mod289(vec4 x);
- float permute(float x);
- vec3 permute(vec3 x);
- vec4 permute(vec4 x);
- float taylorInvSqrt(float r);
- vec4 taylorInvSqrt(vec4 r);
- vec4 grad4(float j, vec4 ip);
- float F4 = 0.309016994374947451
- float snoise(vec4 v);
- float snoise(vec3 v);
- float snoise(vec2 v);
- float hifi_hash(float n);
- float hifi_noise(in vec2 x);
- float hifi_fbm(in vec2 p);

- float DEFAULT_ROUGHNESS = 0.9;
- float DEFAULT_SHININESS = 10.0;
- float DEFAULT_METALLIC = 0.0;
- vec3 DEFAULT_SPECULAR = vec3(0.1);
- vec3 DEFAULT_EMISSIVE = vec3(0.0);
- float DEFAULT_OCCLUSION = 1.0;
- float DEFAULT_SCATTERING = 0.0;
- vec3 DEFAULT_FRESNEL = DEFAULT_EMISSIVE;

- TransformCamera getTransformCamera()
- where a TransformCamera is:
struct _TransformCamera {
    mat4 _view;
    mat4 _viewInverse;
    mat4 _projectionViewUntranslated;
    mat4 _projection;
    mat4 _projectionInverse;
    vec4 _viewport;
    vec4 _stereoInfo;
};
- int gpu_InstanceID()
- vec3 getEyeWorldPos()
- bool cam_isStereo()
- float cam_getStereoSide()

- float isUnlitEnabled()
- float isEmissiveEnabled()
- float isLightmapEnabled()
- float isBackgroundEnabled()
- float isObscuranceEnabled()
- float isScatteringEnabled()
- float isDiffuseEnabled()
- float isSpecularEnabled()
- float isAlbedoEnabled()
- float isAmbientEnabled()
- float isDirectionalEnabled()
- float isPointEnabled()
- float isSpotEnabled()
- float isShowLightContour()
- float isWireframeEnabled()
- float isHazeEnabled()
- float isBloomEnabled()
- float isSkinningEnabled()
- float isBlendshapeEnabled()

### Version 1

- must implement `vec3 getProceduralColor()`
- always emissive, just returns a single color

### Version 2

- must implement `float getProceduralColors(inout vec3 diffuse, inout vec3 specular, inout float shininess)`
- the method can optionally set `diffuse`, `specular`, and `shininess`, but doesn't have to
- shininess goes from 0 to 128
- return value is "emissiveAmount".  If it's greater than 0, the object will be treated as emissive

### Version 3

- must implement `float getProceduralFragment(inout ProceduralFragment proceduralData)`
- ProceduralFragment struct:
struct ProceduralFragment {
    vec3 normal;
    vec3 diffuse;
    vec3 specular;
    vec3 emissive;
    float alpha;
    float roughness;
    float metallic;
    float occlusion;
    float scattering;
};
- method can optionally set any of the values in the struct to affect the output
- return value is `emissiveAmount`

### Version 4

- must implement `float getProceduralFragmentWithPosition(inout ProceduralFragmentWithPosition proceduralData)`
- ProceduralFragmentWithPosition struct:
struct ProceduralFragmentWithPosition {
    vec3 position;
    vec3 normal;
    vec3 diffuse;
    vec3 specular;
    vec3 emissive;
    float alpha;
    float roughness;
    float metallic;
    float occlusion;
    float scattering;
};
- same as v3 but with per-fragment position.  By modifying position, you can modify the per-fragment depth.  This allows you to create things like raymarched geometry that depth-tests properly and is dynamically lit by light entities.  The trade-off is that this version is much more expensive than v3.

## Transparency

v3 and v4 procedurals support transparency.  For transparency to work, the entity must be marked as transparent.  How you do this depends on the entity type, as some entities allow you to control alpha via an entity property.  However, you can always control the alpha via the "opacity" property of the Procedural Material Entity, like so:

```
{
	materials: {
		"model": "hifi_shader_simple",
		"opacity": 0.5,
		"procedural": {
		  	"version": 2,
		  	"shaderUrl": "https://gist.githubusercontent.com/SamGondelman/1698eaf73d86d6a0c9238abff0116e8d/raw/1aa938de50c1b6f31af8a122f40a7ce331eeb533/Proceduralv2.fs"
		}
	}
}
```

## Zone Entities

NOTE: zone entities actually still only use userData, but I'm hoping to fix that soon and then the userData way of setting procedural data will be deprecated so I wouldn't recommend mentioning it in the docs

Zones operate slightly differently.  They support the same global defines, but mot the provided methods or constants. They also provide the following inputs:

- vec3 _normal;
- Skybox skybox; (a struct containing vec4 color)
- samplerCube cubeMap; (the skybox texture)

And must implement the following method, regardless of version:

- vec3 getSkyboxColor()

Zones also support custom uniforms and textures (currently only 2D textures)

# Vertex shaders

- must implement `void getProceduralVertex(inout ProceduralVertexData proceduralData)`
- ProceduralVertexData struct:
struct ProceduralVertexData {
    vec4 position;
    vec4 nonSkinnedPosition;    // input only
    vec3 normal;
    vec3 nonSkinnedNormal;      // input only
    vec3 tangent;               // input only
    vec3 nonSkinnedTangent;     // input only
    vec4 color;
    vec2 texCoord0;
};

### Custom uniforms and textures

Procedural materials also support up to 4 custom textures and many custom uniforms.  These can be defined as follows:


```
{
	materials: {
		"model": "hifi_shader_simple",
		"procedural": {
		    "version": 3,
		    "shaderUrl": "https://gist.githubusercontent.com/SamGondelman/8bbd39f91d20cab4c75280d9b1cb0764/raw/7930289654ce8309bbe785907f03eabc1dbc6181/Proceduralv3.fs",
		    "uniforms": {
		        "_diffuse": [1, 0, 0],
		        "_alpha": 1.0,
		        "_emissive": [0, 0, 0],
		        "_emissiveAmount": 0.0
		    }
		    "channels": ["https://mario.nintendo.com/assets/img/home/intro/mario-pose2.png", "https://www.mariowiki.com/images/thumb/e/e1/Luigi_New_Super_Mario_Bros_U_Deluxe.png/200px-Luigi_New_Super_Mario_Bros_U_Deluxe.png"]
	    }
    }
}
```

When texture URLs are provided, iChannel0 - iChannel3 will be populated, as well as iChannelResolution[0] - iChannelResolution[3].

When you provide uniforms, you must also include them at the top of your shader file, with optional defaults:

```
uniform vec3 _diffuse = vec3(0.0);
uniform float _alpha = 1.0;
uniform vec3 _emissive = vec3(0.0);
uniform float _emissiveAmount = 0.0;
```

Supported uniform types are: float, vec2, vec3, and vec4 (multiple values are provided as arrays)

**Comment by ctrlaltdavid** [comment]
The: Some of the above (e.g., vertex shaders, I think) is probably post-0.86.

**Comment by odysseus654** [comment]
Heads up, skybox shaders are *very* different from procedural shaders.  From the code I'm seeing in log files:

uniform samplerCube cubeMap;
uniform vec4 skyboxBuffer.skybox.color;
in vec3  _normal;

uniform sampler2D iChannel0;
uniform sampler2D iChannel1;
uniform sampler2D iChannel2;
uniform sampler2D iChannel3;

// required shader declaration:
vec3 getSkyboxColor();

/* Procedural Shaders are expected to be Gamma (2.2) corrected */

**Comment by kasenvr** [comment]
The initial documentation has been created, thank you so much everyone! https://github.com/kasenvr/athena-docs-sphinx/pull/17
