### ISSUE TITLE
Avatar locomotion speed is unnatural

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/project-athena#17]
Original author "ultranique" posted on the roadmap for High Fidelity: 

> I have noticed issues with the avatar locomotion in 82.1, where avatars scaled smaller than 1x move quickly/erratically and skip the walk animation and go directly the the run animation state. The opposite is true of avatars scaled larger than 1x - they move extremely slowly, like walking through molasses. When the avatars are smaller I have also seen some random T-poses blip in after each run animation cycle. I would expect the animation to stay consistent and scale to the size of the avatar to maintain the same frame rate, but it seems that is no longer the case.

**Comment by ctrlaltdavid** [comment]
Repro'd the problem with Woody in Athena core, HiFi 0.86, and HiFi master.
RC 82.1 ... Broken.
RC 81.1 ... Works OK.
Broke in build 10235, commit b10faa8.

10235 (April 04 2019 at 23:18 UTC)
From Pull Request: 14738
Case 21777: Locomotion Project 
The current locomotion prototype from Design Team, from [Joshua's proposal](https://drive.google.com/file/d/1YrkjfVZ4fpoy0BkPJd8DG6CmiZTppRxw/view). 

[Relevant Confluence doc.](https://highfidelity.atlassian.net/wiki/spaces/DES/pages/447218473/Design+Locomotion+Prototype) 

[Relevant MS Ticket](https://highfidelity.fogbugz.com/f/cases/21777/Locomotion-Revamp) 

In order to test, there are a handful of new menu options (see _Settings > Controls_) that were added to toggle features. Please see attached image for a quick run down. 

![ControlLayout](https://user-images.githubusercontent.com/39922250/54954944-2bd21900-4f09-11e9-88af-5374432fbab9.png) 

**Notes:** 
- Menu items have not been run through design and are to demonstrate the toggle-able functionality and its effect on movement. 
- Analog++ custom curves are not fully implemented yet. Analog acceleration curve needs some work to really feel it. 
- The tablet is now accessible only from the menu button on the hand that has translation controls (move forward / strafe). 
- There is now a strafe toggle menu option to disable strafing. 
- Jumping/flying control is now they secondary thumb button on either platform. 
- Flying needs to be tuned heavily.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/55

**Comment by thoys** [comment]
Fixed in merged PR https://github.com/kasenvr/project-athena/pull/55
