### ISSUE TITLE
"textEffect" properties are missing on the Create App.

### ISSUE THREAD

**Issue by AleziaKurdis** [kasenvr/project-athena#217]
The following properties are missing in the "**Create**" app (entity editor) on the "**Text**" entity:
- **textEffect**
- **textEffectThickness**
- **textEffectColor**

I think those are enough intuitive to worth to be added.

I also found those missing properties (I have doubts if they worth to be added):
- "**font**" of the "**Text**" Entity 
(This is a string that supports a finished list of font OR a the Url of a font file. The fact that it's a string make it not very intuitive to use in this editor) 
- "**inputMode**" of the "**Web**" Entity _["touch" (default) or "mouse"]_ 
(How much it is useful to set this to mouse in a VR project ? To be try.)

**Comment by kasenvr** [comment]
The font property sounds like it would be relevant since a link to the font file is something that would likely get used if given the option.

As for inputMode, again I would reckon it's important because some applications may not register a touch event properly. So for some applications that are business or educational, they want to configure that. Would it take up a lot of space?

I think it would be cool to have entity-type-specific properties in the create app at some point, so depending on the type detected, there will be one extra button that will have the properties exclusive to that type entity.

**Comment by AleziaKurdis** [comment]
We can add "**font**" and "**inputMode**" easily.
Maybe we can have the possible values for "font" describe in the tooltip.

Can you assign me this Issue?

**Comment by kasenvr** [comment]
This has been fixed in 2020.2.0 Asteria. :) Thank you for fixing this @AleziaKurdis !
