### ISSUE TITLE
"Throttle FPS if not in focus" toggle broken

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#290]
This was mentioned before, but I couldn't not find a ticket.

To replicate:

-Visit domain with obvious movement
-uncheck develper/render/throttle FPS if not in focus.
-move mouse off the window and click on desktop or another app

Note that Vircadia still becomes throttled.

**Comment by ctrlaltdavid** [comment]
Note commit  f88f5dddedda25d0dc14e2fd7311796d4f7a3837 [f88f5dd] in HiFi master.
"When choosing "Realtime" rendering in custom graphics or if you're using the High Quality graphics setting, the render/game rate should still target 60hz even when the window is focused. This is so that people doing streaming can still have high frame rate rendering when using apps like OBS"

**Comment by Aitolda** [comment]
Thanks David!
