### ISSUE TITLE
AppImage does not run on xenial, ingredients built on too new system

### ISSUE THREAD

**Issue by probonopd** [kasenvr/project-athena#353]
Hi, thanks for making an AppImage.

Please compile on a system no newer than the oldest still-supported Ubuntu LTS (currently xenial) so that the resulting AppImage will run on all still-supported distribution versions.

`/run/firejail/appimage/.appimage-9150/AppRun: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9150/AppRun)`

Reference:
https://github.com/AppImage/appimage.github.io/pull/1988

**Comment by daleglass** [comment]
That's correct, Xenial isn't supported because several of the needed tools including cmake are too old to build the project.

**Comment by probonopd** [comment]
@azubieta maybe you could have a look here? Thanks!

**Comment by azubieta** [comment]
Hello @daleglass!
Please check [appimage-builder](https://appimage-builder.readthedocs.io). It's a new tool for creating AppImages that allows building your AppImages on modern Ubuntu/Debian systems keeping the backward compatibility.

Let me know if you need help

**Comment by daleglass** [comment]
AppImage stuff seems to want a well behaved Linux application. The code doesn't install binaries into /usr, put the various data files in the right places and so on. So getting AppImage to work at all took bypassing all of that. That needs fixing of course.

The second problem is that it just doesn't build without fiddling on Xenial, and using Docker isn't going to fix that.

Since Xenial is already old and has only one year of life left, while this is a bleeding edge piece of software, and I have a list of things to do a mile long, I don't have any plans for supporting Xenial unless somebody just sends me a PR.

**Comment by probonopd** [comment]
> Since Xenial is already old and has only one year of life left, while this is a bleeding edge piece of software, and I have a list of things to do a mile long

Hi @daleglass thanks for responding. I know that supporting everything can be a pain, but please do keep in mind that running the very latest (bleeding-edge) applications on long-term stable (LTS) operating systems is not a contradiction. In fact, it is a quite common combination you will find in many organizations.

**Comment by daleglass** [comment]
Fair enough, but the number of issues with supporting Xenial is significant, and a new one just cropped up.

We're working on integrating Crashpad for Linux crash reporting. Turns out it also doesn't want to compile on Xenial out of the box. So while I tried, so far this seems to be more hassle than it's worth. Of course, if you have some pressing need to run this on Xenial and want to give it a try, I won't say no to PRs with fixes.

But I don't quite see why anybody would need to run this on Xenial in the age of almost universal virtualization and containerization. I would also say as an experimental project, you should treat this with some caution, and give it some separate space.
