### ISSUE TITLE
renderWithZones: zone list incorrectly sorted.

### ISSUE THREAD

**Issue by Nex-Pro** [kasenvr/project-athena#354]
List of zones does not appear to be sorted.

Scroll handle does not respond or is very intermittent.

![stressTestCaptureZones](https://user-images.githubusercontent.com/7314019/82126295-b4fa7e00-97a3-11ea-88cc-04f7550065cc.PNG)

**Comment by Nex-Pro** [comment]
The scroll handle doesn't work as expected if I try to drag it down nothing happens.
Occasionally it gets hooked to the curso and drags unexpectedly.
Clicking in the scroll bar above or below the handle seems to work ok.

**Comment by AleziaKurdis** [comment]
Zones are indeed not sorted, they are in the order returned by the method "**Entities.findEntitiesByType**"
Doing a sort might have certainly a cost in performance. 
But it worth to be tried since it's going to be a pain to use with a large ensemble of zones.
---
For the scroll bar issue. This is a simple HTML select. 
Is that caused by the high quantity of items?
If it's the case, I don't see too much what can be done unless we change the design. (I'm open to suggestion)

**Comment by AleziaKurdis** [comment]
I noticed in the past that "select" is problematic when we build a tablet app.
I remember having to change for a radio list
because the list of items of the selector was displayed outside the tablet (in my other monitor)
There is something unstable deeper for that component.

**Comment by AleziaKurdis** [comment]
Sorting as been added (PR: **Zones Selector sorted by zone names #369**)
I tested this with 952 zones and that was still performant.

The issue with the scrolling is still present. I don't know how to address this. Is that a Web browser Component implementation issue? or any CSS interference (VR(mobile way) versus Desktop) 
I suggest that we open a separate issue if you agree.

**Comment by kasenvr** [comment]
The sorting issue has been solved, we should open another issue about the UI not responding correctly to user input intermittently. :)
