### ISSUE TITLE
Feature: Particle system "prewarm"

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#479]
Particle systems only run when you look at them (sort of), that is how it should be, but it does mean that it restarts a lot if you happen to look away. For systems with long lifetime. slow moving particles, like a waterfall or a big fire, it completely breaks the illusion because they may need a few seconds of emitting, before they look right.

In Unity, there is an option called "prewarm" to solve this, it basically lets you start the effect, not from 0, but from how it would look after, say 2 seconds of running.

**Comment by HifiExperiments** [comment]
The above PR doesn't add the prewarm feature, as I'm still thinking through how best to do it.

However, the behavior you describe was actually a bug.  When you look away from particles, they're supposed to pause as-is, not completely disappear.  The bug was that when you looked away, the first time you looked back, they would get a big timestep and all the particles would die.  Now, they really pause.  So when you first go to a domain or create a particle, they will still need to "warm up", but after that, they will not reset.
