### ISSUE TITLE
Blendshapes not supported on GLTF(glb) models

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#495]
Applies to both avatars and entities but especially important if we want to support GLTF avatars

**Comment by SilverfishVR** [comment]
These are the same model in _fbx, glb_ and _gltf_ format, thay have "UserBlendshape0" and "UserBlendshape1" that morph their shape:
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/BlendShapeTest/MorphCubeUserBlendShapes.fbx
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/BlendShapeTest/MorphCubeUserBlendShapes.glb
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/BlendShapeTest/MorphCubeUserBlendShapes.gltf

use `Entities.editEntity("[UUID]", {blendshapeCoefficients: JSON.stringify({"UserBlendshape0": [VALUE]})})` to set blendshape, or load this json with all 3 models and a script that updates the blendshapes continuously:
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/BlendShapeTest/MorphCubes.json

**Comment by Colorfingers** [comment]
I will put up $100 US toward the bounty to fix this issue...

**Comment by ctrlaltdavid** [comment]
I can have a look at this after I emerge from some project work - probably in a couple of weeks.

**Comment by ctrlaltdavid** [comment]
I've started having a look at this.

**Comment by ctrlaltdavid** [comment]
Blendshapes aren't documented in the user docs very well: https://github.com/kasenvr/vircadia-docs-sphinx/issues/58

**Comment by ctrlaltdavid** [comment]
glTF/GLB files can currently be used for avatars provided an FST file is used to map the blendshapes.
FBX files can be used for avatars with or without FST files to map blendshapes.
I anticipate the glTF/GLB files will be able to be used without FST files once the support for using blendshapes in general model files (without FST files) is fixed.

**Comment by Colorfingers** [comment]
Here's my experience with this PR... The eyeblink and jawopen morphs are working but are extremely exaggerated. I tried loading it with the fst but that only crashes my interface.  Another issue has risen.  The texture for the eyes does not load.  The skin texture loads properly and that texture is applied in the MakeAvatar app as is the eye texture.  I opened the glb file into blender and the eye texture loads there.  I tried in an older interface and the eye texture does not load there either.  I think that it loaded earlier perhaps because it was baked in the original glb file that the export is based upon.  I will play with changing some values in the base avatar file to see if I can find values that work properly.  Does anyone have a script that can run to test out all of the existing blend shapes?  Here are my source files if anyone wants to take a stab at playing with it in this PR.  If someone can look at my fst file and tell me what I may be doing wrong that would be great.  I tried it several ways with limiting it without the bone maps.... https://hapticmonkey.s3-us-west-1.amazonaws.com/avatar.fst https://hapticmonkey.s3-us-west-1.amazonaws.com/avatar.glb

I changed the max value to 0.001 in Blender for all three which is the lowest I can set the morphs.  That did not work.  You can see that in https://hapticmonkey.s3-us-west-1.amazonaws.com/avatar2.glb the amount of deformation has not changed.  The original for JawOpen was 0.5 and both Eyeblinks were set to a max of 1.  I don't think the problem is in the value but in something else...

**Comment by kasenvr** [comment]
All participants have agreed that the bounty is fulfilled. The issue is now closed, thanks so much for everyone's participation! :)
