### ISSUE TITLE
Angular Velocity in create app is using deg/sec instead of rad/sec 

### ISSUE THREAD

**Issue by 1st-BrainStormer** [kasenvr/project-athena#530]
The create app is using degrees per second instead of radians per second. the si unit of angular velocity is Radians per second. In the API its radians/sec and when exporting the entity it is also. Having the create app show it as degrees per second is confusing.      Also the create app should show units for all physics properties.

**Comment by ctrlaltdavid** [comment]
The UI is all in degrees. This is intentional because people typically relate to degrees better than they do radians. (For example, to do a quarter turn on an entity, enter 90 degrees rather than 1.570796 radians.)

The API is in a mixture of degrees and radians.

Showing units in the Create app would be good, I think.

**Comment by 1st-BrainStormer** [comment]
Well this is angular velocity not rotation. Most people relate to revolutions per minute not degrees per second. Perhaps a button that switches between units.   I just find it annoying that in the JSON file of exported entities has a value that doesn't match that in the create app.  Now with the tabs in the create app giving you more room, you could have both units displayed and updated when the other fields are edited.

**Comment by ctrlaltdavid** [comment]
Ability to switch between units is a good idea.

**Comment by AleziaKurdis** [comment]
> Showing units in the Create app would be good, I think.

Actually, the unit is there, but in the tooltip. It says: Rad/s
![image](https://user-images.githubusercontent.com/60075796/89319244-d86bf100-d64d-11ea-9fd3-080dfff04373.png)

So there is something to fix:
- The **UI fields**
**_OR_**
- The **Tooltips**

I'm not sure about switchable units only for one field.
(Certainly not an option for the entire UI either, no one would like to deal with the rotation exposed in radian)
There is not that much space it that UI. (it's not a very flexible UI)
A unit switch would require to do an exception or a new field type used for only one field.

For "**Angular Velocity**", I would recommend going with **Rad/s**, which means to fix the UI field.
- This is a physic concept, closer to the mathematic (in radian) than the measurement usage (which is better in degree)
- Angular Velocity is explained in Rad/s all over the web and in the physic theories.
- It's the official unit (over rpm and deg/s)
- Other systems also used the rad/s unit (even Second Life: http://wiki.secondlife.com/wiki/LlTargetOmega)

If you are ok with that suggestion, let me know I could work on that.
But if you prefer to keep **deg/s** and have the Tooltip changed for **deg/s**, I can also do that.
Just to assign me to issue.
 
I would also take the opportunity to revisit the tooltips for the 2 Damping fields. It's not too much detailed.

**Comment by 1st-BrainStormer** [comment]
To me the exported JSON and the UI should use the same units.

**Comment by JulianGro** [comment]
Personally degrees per second or revolutions per minute makes more sense to me. RPM is used so much that even people without education should know that it is a unit of rotational speed. Degrees per second is very easy to visualize.

Radians per second on the other hand might be used in physics, but personally I have never heard of that. People also cannot really guess what it describes "What the heck is a radian?".  And if someone like me, who is fairly highly educated, has never heard of radians, then there will be a lot of other people who never have as well.

**Comment by AleziaKurdis** [comment]
I suggest we disqualify "RPM"

The field name being "Angular Velocity", it makes more sense that the unit reflects an "angle" per time interval.
RPM is the "number" of a specific angle ("360 degree") per minute. 
This is less easy to convert when you jump to the API/script side. Not that much complex, but scripted are used to do the common deg - rad conversion )

Also Wikipedia: According to the International System of Units (SI), rpm is not a unit. This is because the word revolution is a semantic annotation rather than a unit.
