### ISSUE TITLE
"Render with Zones" does not work on parented materials

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#560]
Zone occlusion works for material entities, but not for parented material entities, and material entities needs to be parented to be useful.
So, for a shape, or model with a material applied to it (by a child material entity) the expected behaviour would be that if the material entity has it's "render with zones" property set, the "material override" would only be in effect when the user is in that zone, currently that is not the case and the override is always active.

below. 2 material entities, one is parented to the cube and both are set to only render with the zone I am entering
![vircadia-snap-by-Silverfish-on-2020-07-21_00-36-43](https://user-images.githubusercontent.com/53531160/87993425-bff6c500-caea-11ea-8f55-83d3b7857d72.gif)

Here is a json of the setup but note that the "render with zones" will be broken and needs to be reapplied, separate issue.
https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/testMaterialOcclusion.json

**Comment by HifiExperiments** [comment]
huh, I never considered this.  the problem is that this would add a lot of complexity to the system that could affect performance.  for every model, not only do you have to check the zones you are in, but also for each material on each mesh part (and in some cases, multiple materials if the first materials don’t render).

but also logically, the material entity exists as a way to apply a material to something, but once it does, the material rendering is the responsibility of the model.

so...I think the easiest solution here would be to handle this via script, but I’m also curious what the use case is?  If you’re trying to replicate LOD or something, we should handle that in other ways anyway

**Comment by Aitolda** [comment]
It is indeed an attempt to replicate LOD.

**Comment by Aitolda** [comment]
> huh, I never considered this. the problem is that this would add a lot of complexity to the system that could affect performance. for every model, not only do you have to check the zones you are in, but also for each material on each mesh part (and in some cases, multiple materials if the first materials don’t render).
> 
> but also logically, the material entity exists as a way to apply a material to something, but once it does, the material rendering is the responsibility of the model.
> 
> so...I think the easiest solution here would be to handle this via script, but I’m also curious what the use case is? If you’re trying to replicate LOD or something, we should handle that in other ways anyway

It is indeed an attempt to replicate LOD, at least to some extent.

**Comment by HifiExperiments** [comment]
I would be careful with that.  It’s possible that using multiple materials like this won’t really help performance, but it will use a lot more memory.
