### ISSUE TITLE
"Render With zones" does not load from json

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#562]
well, it does, but what is saved in the json is the UUID of the zone, not the name (and render with zones is selected by name), when loading a content set that uses zone occlusion, it fails because the UUID's are different.

P.S. I know, I tested zone occlusion prior to merge but clearly not that well 😞 I will do better next time.
use the json from #560 to test: https://silverfish-freestuff.s3.eu-north-1.amazonaws.com/TestStuff/testMaterialOcclusion.json

**Comment by AleziaKurdis** [comment]
This always been by id. 
Not sure it would be optimal to use names, which are not unique or can be null.

The problem is the json import.
It should be able to resolve any kind of parenting the parent based on the UUID from the json (this is also true when a serverless domain is loaded). Maybe by keeping the old id values during the generation to always be able to find the new id to use.
Don't know if this already exist, maybe it has been simply forgotten for renderWithZones.

**Comment by SilverfishVR** [comment]
I think render with zones is a bit different, in that the entity may not be a child of the zone (I tried that too, samesame) so it can't really use that reference, if you exported the zone too, like I did, the name of the zone is in the same json, with matching ID's so would be possible in that case.
I know there are other ideas on how to expand/improve the system, so maybe hold on to this until we know what we want

**Comment by HifiExperiments** [comment]
yeah we already do this with parent ID, remapping it to the new one.  I neglected to add it for renderWithZones, but it should be an easy fix.
