### ISSUE TITLE
Rename Interface to just Vircadia

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#647]
For new users, "Interface" is a very overcomplicated was of referring to the Vircadia Client. I think to make it easier for everyone, it would make sense to just call it "Vircadia", "Vircadia Client" or maybe even "Vircadia Interface". Though I think if someone actually had multiple Vircadia executables "Vircadia" would make it more obvious that this is what they want if they have no idea.

If we decide to do this, there is multiple areas where this would need to be changed:

Windows:
- [ ] rename interface executable
- [ ] check and rename link to interface executable
- [ ] check and rename occurrences in launcher

Linux:
- [ ] rename executable? (this isn't needed as you will likely never interact with the executable directly)

MacOS:
- [ ] rename executable (interface.app)

Documentation:
- [ ] check and fix occurrences

**Comment by kasenvr** [comment]
I think the reason that High Fidelity named it Interface was so that the concept retains past just Vircadia. We expect Vircadia to be at the forefront but just like the early days of the internet, anyone could make a "browser", and so the name browser has stuck.

I think if we keep the words Interface and then just have the shortcuts at least say Vircadia then that'll be easy enough. #651

**Comment by ctrlaltdavid** [comment]
"Vircadia Interface" makes sense to me.
