### ISSUE TITLE
Builder's Grid on 3.0 Demeter is misaligned and rotated.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#764]
IBuilder's Grid on 3.0 Demeter is misaligned and rotated.  Ideally if you are using the grid you'll want it set to 0,0,0 on the rotation and aligned to an even increment.  Image below demonstrats where a snapped cube is in relationship to the grid.  Just to note this goes back before Vircadia to HF, but I was freshly reminded of this when testing out the new stripped-down sandbox.

[Screenshot](https://i.gyazo.com/02b0a4c6f26e01e98ab5a4f520927adc.png)

**Comment by SilverfishVR** [comment]
should be fixed in the release version if you want to check. I reset rotation to 0,0,0 (or as close as it will let me) and position so the 4 grids meet a 0,0,0.
![Screenshot 2020-09-29 22 57 55](https://user-images.githubusercontent.com/53531160/94615210-a8d11200-02a7-11eb-9c18-c7e04c63ef44.png)
and removed some ghost entities that floated around several km away

**Comment by Aitolda** [comment]
This has been fixed post-RC.
