### ISSUE TITLE
in-app browser is out of date

### ISSUE THREAD

**Issue by SilverfishVR** [kasenvr/project-athena#90]
whatever flavor of Chromium (it's chromium right?) seems out of date, many pages, including github, show a message that the browser is no longer supported
![Skærmbillede 2020-01-14 01 36 10](https://user-images.githubusercontent.com/53531160/72303669-49c26300-366e-11ea-9195-b2800f499a0c.png)

**Comment by MarcusLlewellyn** [comment]
The interface makes use of Qt for it's web browser, which in turn uses the Chromium Embedded Framework (or CEF). What this means for Athena is in order to upgrade CEF, we need to upgrade Qt. Currently, we're using Qt 5.12.3. There is a newer version of Qt we could look into using; Qt 5.14 is now the latest LTS release.

**Comment by kasenvr** [comment]
What is the reason for High Fidelity's shipping their own Qt version? Are there many changes? I wonder what would break if we try to make that upgrade.
