### ISSUE TITLE
Scroll bars do not appear in some menus where scrolling is necessary.

### ISSUE THREAD

**Issue by Aitolda** [kasenvr/project-athena#98]
Users are unable to see the additional settings farther down the menu.

1. In desktop mode, go to settings.
2. Select "Controls."
3. click somewhere on the menu and drag upward. More options will be revealed.

**Comment by ctrlaltdavid** [comment]
Also occurs in Settings > Audio
Both problems occur in latest master.

**Comment by ctrlaltdavid** [comment]
The following settings dialogs have more content than can be displayed in one screen:
- General
- Audio
- Controls

Of these, only General displays scrollbars.
And then only in non-tablet mode.
In both tablet and non-tablet mode, the content can be scrolled by clicking and dragging the content.

Q: For these three dialogs, should scrollbars be displayed:
(a) only in non-tablet mode.
(b) in both tablet and non-tablet modes.

I'd tend towards (b) because even though the scrollbar's not really usable in HMD tablet mode (too small) it does provide a visual indicator that there's more content on the page that can be scrolled to.

**Comment by Aitolda** [comment]
I think (b) for consistency.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/project-athena/pull/113
